### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by howardroark** [laktak/hjson#14]
I think you would have a lot of success if you had a python tool available @ [pypi](https://pypi.python.org/pypi).  From a systems admin perspective, this format could be very useful.  A good deal of text based object configuration goes on, and on a daily basis.  YAML is fine sure, but why not have the option to try something else.

Python has a pretty active community.  If you just threw together something scrappy, I'm betting people would clean it up pretty quickly.

The JavaScript community is going to be naturally hesitant to something like this.  Mainly because it is "suggestive" about standards.

Just a thought!

**Comment by laktak** [comment]
@Rast1234 That's great! What are you using as a base?

**Comment by laktak** [comment]
@howardroark interesting project.

**Comment by howardroark** [comment]
It is a really powerful tool (inspired by cfengine).   You define your machine state as text based objects which are parsed using the [Jinja2] template engine at runtime.  Right now I use YAML, but it can start looking really awkward when broken up in templates because of the whitespace requirements.  With HJSON I could ensure that the whitespace works for reading the file before it is parsed.  If that makes sense!

[Jinja2]: http://jinja.pocoo.org/

**Comment by laktak** [comment]
I just pushed a Hjson parser to https://github.com/laktak/hjson-py - please take a look!

**Comment by howardroark** [comment]
I'll check this out! Smart idea forking simplejson and leveraging all the python jazz!

**Comment by howardroark** [comment]
I made an issue with Salt to see if there is any interest in that community... https://github.com/saltstack/salt/issues/19374

:)

**Comment by laktak** [comment]
@Rast1234 I hope you'll find it useful! Could you run some tests on it?

Also if you have time, dump still needs to be implemented ;-)

**Comment by laktak** [comment]
[hjson-py](https://github.com/laktak/hjson-py) is now fully implemented in v1.4 :-)
