### ISSUE TITLE
Allow additional characters in keys.

### ISSUE THREAD

**Issue by howardroark** [laktak/hjson#16]
I understand the the current implementation only allows `alphanumeric` characters in `keys`, but I find that can lead to mistakes very easily.  It would be great if the goal of HJSON was to cater to as many potential human errors as possible. Basically accept that no one will read the docs thoroughly and go on to assume things about the nature of the format.  A large assumption would be that hyphens and underscores in keys would be catered for.

If I were to make a key for something like `redis-server` I don't think my mind would clue in that I am typing a non-alphanumeric character.  At least not until I am debugging the error later... or maybe not even ;)

**Comment by laktak** [comment]
I changed it to allow all characters except whitespace and `{}[],:` (because that would make it confusing).

Thanks for the feedback!
