### ISSUE TITLE
Optional outermost braces.

### ISSUE THREAD

**Issue by howardroark** [laktak/hjson#17]
So I was thinking (and feel free to shut this one down)...   It might be cool if the parser assumed that the contents being parsed were an object vs array if no outermost braces were present.  I feel like this would make files look a bit more clean... especially if you had no nested properties.

**Comment by laktak** [comment]
I thought about this as well but decided against it.

- The braces aren't a source for common mistakes.
- They actually give the user a clue about the format - we still want it to look similar to JSON.

**Comment by howardroark** [comment]
Sold. New people. Makes sense :)

**Comment by laktak** [comment]
See #28

**Comment by laktak** [comment]
@howardroark it took a while but it's now fixed :)
