### ISSUE TITLE
Feature request: PHP port

### ISSUE THREAD

**Issue by smartcorestudio** [laktak/hjson#19]
It will be great if someone will write php wrapper for it, like it was made for python...

**Comment by laktak** [comment]
Maybe you could try to ask in PHP groups/reddit if someone is interested in porting it?

**Comment by iainhallam** [comment]
I've got a quote from People Per Hour for this, and opened a GoFundMe to help fund the development as open source:

https://www.gofundme.com/php-hjson

I'd greatly appreciate some support there, and also any thoughts on which licence to use.

When the implementation is done, it can go on GitHub with the others, and I've specified that a Composer module on Packagist should be part of the work.

**Comment by laktak** [comment]
That's great! 

I've linked from hjson.org to this issue, hope it helps.

**Comment by howardroark** [comment]
I remember when @laktak created the python version it was a matter of forking simplejson and adapting from there.  This project might give you some ideas... https://github.com/itspriddle/json-php

Unless the intention is to write a PECL extension in C :P https://github.com/remicollet/pecl-json-c

**Comment by howardroark** [comment]
@iainhallam Maybe you could kick off a base repo for the project on GitHub?

**Comment by laktak** [comment]
If you can find a PHP port of https://github.com/douglascrockford/JSON-js it should be fairly easy to make it support Hjson by following the changes in hjson-js.

**Comment by pmoust** [comment]
Hello @iainhallam , 

I'm a member of PeoplePerHour DevOps team, just stumbled across this issue after our freelancer<->client algorithm kicked in and pinged me to check your job posting out.

I'd happily contribute a Lexxer for HJSON to be used as a PHP library via Packagist but it happens that I am terribly busy, so I can't issue an ETA.

Do let us know how your experience was using our platform.

**Comment by iainhallam** [comment]
I've funded this work now, so it will go ahead soon. Can the finished work end up under the laktak GitHub space with the other implementations? I think I'd prefer it to be under an account in that name on Packagist for the Composer package, if that's OK as well.

**Comment by laktak** [comment]
@iainhallam That's great to hear! 

I've created a new repo and added you as a collaborator at https://github.com/laktak/hjson-php

Let me know if you need anything else.

**Comment by iainhallam** [comment]
@laktak, have you got an account on packagist.org the PHP Composer package can live in?

**Comment by laktak** [comment]
Not at the moment. But please do add the Hjson test cases if you want me to publish the package.

**Comment by laktak** [comment]
@iainhallam Just discovered that you can use a GitHub Service Hook to auto update the packages there. So you should be able to publish yourself once the initial setup is complete.

**Comment by iainhallam** [comment]
There's now a version in https://github.com/laktak/hjson-php - anyone want to test?

**Comment by howardroark** [comment]
What is the preferred way to get started with a PHP project in general?  Is there some sort of composer command?  To have some files that say "this project requires hjson".

**Comment by iainhallam** [comment]
Not at present, but a Packagist package will be added once we're happy with the implementation. For now, just use the version on GitHub for testing.

**Comment by laktak** [comment]
@iainhallam I installed PHP yesterday and got the tests and the sample working. Looking good!

**Comment by iainhallam** [comment]
@laktak, the composer.json file currently suggests hjson/hjson as the name of the package for Packagist. Should that be laktak/hjson? I'm not particularly looking to make it iainhallam/hjson.

**Comment by laktak** [comment]
laktak/hjson is OK. Just let me know when I should create the first package. Afterwards you should be able to update the package by pushing to github.

**Comment by iainhallam** [comment]
As far as I'm aware, it's ready to go.

**Comment by laktak** [comment]
It's now live at https://packagist.org/packages/laktak/hjson. I had to create a `v1.0.0` tag for the version to appear (the one in composer.json is apparently ignored). I've also added a hook so any commits/tags by you will trigger an update at packagist.

I'll add links from hjson.org later.

Great work, thanks!
