### ISSUE TITLE
Feature request: optional top-level braces

### ISSUE THREAD

**Issue by fwextensions** [laktak/hjson#20]
It's probably a bit late at this point, but if the goal is to make it easy for non-JS developers to edit these files, the top-level braces seem superfluous.  If they were optional, you could make very clean settings docs that contain only key/value pairs, like:

    foo: 42
    bar: ["baz", "asdf"]

The parser would need to check if the first thing it finds is a key, and then add the braces if it is.  Braces could still be required for sub-objects:

    foo: 42
    bar: ["baz", "asdf"]
    more: {
        one: 1
        two: 2
    }

(Potentially, even braces on sub-objects could be made optional by requiring the sub-object keys to be indented consistently, but that's probably more trouble than it's worth.)

**Comment by laktak** [comment]
See #17.

If someone is editing the file the braces are already there so I don't really see any value in removing them.

Also *checking if it is a key* is a bit harder with Hjson's relaxed syntax.

**Comment by laktak** [comment]
See #28
