### ISSUE TITLE
Feature Request: Define a date literal

### ISSUE THREAD

**Issue by adamzr** [laktak/hjson#21]
Create a standardized form for writing date/time values. I'm thinking that in HJSON, we would accept multiple standards of easily readable unambiguous date formats. For example:
 - Jan 1, 2000
 - 5:00 pm
 - January 3rd 2015 13:01

These would all be converted to the same standardized ISO 8601 string in JSON.

**Comment by laktak** [comment]
I thought about this but there are a few problems. 

Handling dates is very hard and often depends on the context/location (e.g. is 1/2 Jan 2 or Feb 1, also DST for times ...). The Hjson parser does not have that context (might run on a server with different settings than the user) and would produce incorrect results. 

Also I'd like to stay with the JSON types and avoid adding others.

But thanks for the input.
