### ISSUE TITLE
Escaping comments

### ISSUE THREAD

**Issue by matthew-dean** [laktak/hjson#24]
Say I have this structure: 
```
prop: {
  foo: #bar
}
```
If I want the value of "foo" to be "#bar", how would I escape comments? Is there any way to do it other than enclosing everything in quotes?

**Comment by laktak** [comment]
No, quoteless strings do not have escapes.
```
{
  prop: {
    # you can use
    foo1: "#bar with escapes like \t"
    # or
    foo2: '''#bar without escapes'''
  }
}
```

**Comment by matthew-dean** [comment]
Got it, thanks!
