### ISSUE TITLE
Optional curly brackets

### ISSUE THREAD

**Issue by og2t** [laktak/hjson#26]
I was reading the hjson intro where you were dropping off all the unnecessary things, got pretty excited there but then you didn't drop the curly brackets in the end (CSON style). Would you consider that in favour of whitespace indentation?

**Comment by laktak** [comment]
Commas and quotes were dropped to make the format easier to edit and less error prone. IMO dropping the curly braces would not help but introduce errors that are hard to detect (e.g. spaces vs tabs).
