### ISSUE TITLE
Explicitly support NaN, Infinity, -Infinity for number type

### ISSUE THREAD

**Issue by bondolo** [laktak/hjson#27]
One of the most frustrating aspects of JSON numbers is lack of support for NaN, and the two infinities. It would be really nice if HJSON supported them.

**Comment by JamesGosling** [comment]
Years ago I wrote my own JSON parser that implements most of what hjson does.  I'd happily trash my parser except for one showstopper: supporting NaN and the two infinities.  I strongly support fixing this issue.

In the parser I've been using, NaN and the infinities are recognized only in unquoted strings.  "NaN" is a string, not a number.  The matching ignores case, and the keywords for the infinities are "inf" and "-inf".  The IEEE754 spec uses "inf" and "-inf" in expressions, "infinity" in sentences.

**Comment by laktak** [comment]
So far I tried to stay within JSON's supported types but I'll consider it. 

Is there any specific use case?

**Comment by JamesGosling** [comment]
On Apr 16, 2015, at 11:43 AM, Christian Zangl <notifications@github.com<mailto:notifications@github.com>> wrote:

So far I tried to stay within JSON's supported types but I'll consider it.

Is there any specific use case?

Every place where floating point numbers are used is a use case.  The IEEE 754 spec (which is where the universally-used float & double types are specified) requires NaN and Inf.  They are numbers just like the ones that people are more commonly used to.  They arise naturally as a part of arithmetic operations: Inf = 1/0; -Inf = -1/0; NaN = 0/0.  Arrays of floats and doubles frequently contain NaN and Inf as values across a wide range of applications.  A specific case that comes up often is that NaN is used for “don’t know”.

Math is impossible without them.

**Comment by laktak** [comment]
@JamesGosling ah sorry, what I meant to ask was if you are planning to use it for configuration/definition files. Hjson is not suited to be used as a protocol for services.

I've taken a look at existing libraries. Some allow the use of infinity/NaN as an optional feature (e.g. [Jackson](http://jackson.codehaus.org/1.8.1/javadoc/org/codehaus/jackson/JsonParser.Feature.html), json5, etc.).

For Hjson we could add support for

- NaN
- Infinity/-Infinity
- Inf/-Inf

without breaking anything (Hjson would just roundtrip it as a string if the feature is not enabled).

**Comment by JamesGosling** [comment]
On Apr 18, 2015, at 6:17 AM, Christian Zangl <notifications@github.com<mailto:notifications@github.com>> wrote:

@JamesGosling<https://github.com/JamesGosling> ah sorry, what I meant to ask was if you are planning to use it for configuration/definition files. Hjson is not suited to be used as a protocol for services.

The hjson-like thing we’re using now is often used for configuration files where NaN is commonly used for “unknown”.
We do use it as a protocol for services, where it works quite well.  I’ll do things like open up a TCP connection and stream JSON both ways.  One of the advantages of hjson-ish things is that the files are more compact: Almost no quote characters.

I've taken a look at existing libraries. Some allow the use of infinity/NaN as an optional feature (e.g. Jackson<http://jackson.codehaus.org/1.8.1/javadoc/org/codehaus/jackson/JsonParser.Feature.html>, json5, etc.).

For Hjson we could add support for

  *   NaN
  *   Infinity/-Infinity
  *   Inf/-Inf

without breaking anything (Hjson would just roundtrip it as a string if the feature is not enabled).

that would be lovely!

**Comment by hildjj** [comment]
@JamesGosling if you're looking for a more compact wire format, including full IEEE754 support, try [CBOR](http://cbor.io/), [RFC7049](https://tools.ietf.org/html/rfc7049).  That said, I do support adding NaN, inf, and -inf to hjson.

**Comment by laktak** [comment]
Hjson already allows you to write `Inf`, `-Inf` and `NaN`. These are parsed as strings by Hjson and can be converted by the app. This allows you to use the syntax you like without having to extend the Hjson grammar.
