### ISSUE TITLE
Outer braces needed?

### ISSUE THREAD

**Issue by matthew-dean** [laktak/hjson#28]
What about making the "outer" braces implied if they're ommitted? So that a config file could be:
```
setting-1: val
setting-2: val
setting-3: val
```
instead of:
```
{
  setting-1: val
  setting-2: val
  setting-3: val
}
```
The outer braces seem unnecessary.

**Comment by laktak** [comment]
This has come up a few times now and while I thought the braces weren't a big deal they apparently are ;)

I'll try to find a solution.

**Comment by matthew-dean** [comment]
Well, I don't think it's so much a big deal as HJSON seems to eliminate every unnecessary thing out of JSON, except for this. The braces don't change the meaning, making them meaningless. The parser could detect if the first non-space character is a brace, in which case it expects a final closing brace. Otherwise, expect that the first token is a key.

**Comment by laktak** [comment]
This should now work in all implementations.

**Comment by matthew-dean** [comment]
Yeeeees so awesome!
