### ISSUE TITLE
Commas in string values fail round tripping

### ISSUE THREAD

**Issue by stevage** [laktak/hjson#29]
Enter this code in the JSON box at http://hjson.org/try.html
```
{
  "foo": "1,2"
}
```

It's converted to this syntactically-invalid Hjson:

```
{
  foo: 1,2
}
```

Try editing that, and see this error message:

`Error: Key names that include {}[],: or whitespace require quotes at line 3,0 >>>} ...`

Seems to be a problem only with lines that can be understood as arrays. For instance this is ok: `foo: hello(1,2)`

**Comment by laktak** [comment]
Thank you for reporting this! I'll take a look.

**Comment by laktak** [comment]
Fixed
