### ISSUE TITLE
Spaces in key names

### ISSUE THREAD

**Issue by stevage** [laktak/hjson#30]
Just wondering if you considered (or would consider) not requiring quotes for keys with internal spaces. It seems unambiguous:

```
my key: {
  has another key: with a string value
}
```

**Comment by nick-ulle** [comment]
:+1:  The current README gives the impression that this already works. It would be a nice feature to have.

**Comment by laktak** [comment]
I'm a bit split on this mainly because I think it makes it harder to find errors. E.g. a syntax error would be reported a line later.

I'll leave this open for now.
