### ISSUE TITLE
Errors due to missing quotes are misleading

### ISSUE THREAD

**Issue by stevage** [laktak/hjson#31]
Just spent a little while chasing down an error of this form:

```
my: {
  test: { thought: this, might: work }
  error: "Shows up at the end of the document"
}
```

The problem is you need quotes around the object values on the second line. But for some reason the error is not at all helpful:

> Error: Bad object at line 4,2 >>>} ...

(In my case it was more like line 250...)

**Comment by laktak** [comment]
Thanks. I'll try to improve the error message even if figuring out the actual line might be impossible.

**Comment by laktak** [comment]
Should be more helpful now:
> Error: End of input while parsing an object (did you forget a closing '}'?) at line 4,2 >>>} ...
