### ISSUE TITLE
Hexadecimal numbers

### ISSUE THREAD

**Issue by jminer** [laktak/hjson#36]
I'd like to have support to write numbers in base 16.

```
address: 0x08000000
```

It'd be useful in configuration files of where to load software in embedded processors. Hex numbers would be the same data type so they could still be represented in JSON without losing information.

**Comment by laktak** [comment]
Is it just an address or would you also need to put binary data into a config file? I think it would make more sense to handle this in the application. That way you can support every use case (data that can't be interpreted, like hex/blob/etc., is available to the application as a string).

**Comment by FHTheron** [comment]
Same request, same reasons. The values are mostly addresses (64-bit at most), but sometimes configuration values that read better as hex numbers.

Handling this in the application is simple enough, but being able to read these as numbers in the file is more useful than reading them as strings (syntax highlighting assumed)

**Comment by sbrl** [comment]
What about hex colours? I'd like to be able to use hex for those.

**Comment by laktak** [comment]
As Hjson already allows `address: 0x08000000` (via quoteless strings), the conversion should be handled by the app.

**Comment by laktak** [comment]
@jminer @FHTheron @sbrl Hex is now supported by enabling the hex DSF (currently with JS/Java/C#).

e.g. for JS
```
Hjson.parse(text, { dsf: [ Hjson.dsf.hex() ] });
```
