### ISSUE TITLE
Security improvements: simplify the spec a bit

### ISSUE THREAD

**Issue by d33tah** [laktak/hjson#37]
See the discussion here: https://news.ycombinator.com/item?id=11498077

**Comment by laktak** [comment]
Thanks for the input. Why do you label it as *Security improvements*?

**Comment by twirrim** [comment]
See the comment linked to:

"The thing where you can leave quotes off strings makes me nervous, especially the example where the value is HTML with its own embedded double quotes for attribute values.

Not requiring quotes on strings like that looks like an obvious vector for injection attacks. I guess Hjson isn't designed to be generated automatically, but I'd prefer a format that is easy to generate safely."

**Comment by laktak** [comment]
I don't see how quoted vs unquoted strings are different in this regard.

If you want to guard against injection you should always use the API (either JSON or Hjson). 

If you really generate JSON by hand (and think that this is safe/safer) then you can pipe it to Hjson at the end.

**Comment by d33tah** [comment]
The thing is that you can't really do anything against having your format used for this kind of purposes.

**Comment by hildjj** [comment]
Having a full formal grammar would probably allow better analysis.  You might start with the ABNF in [RFC7159, Section 2](https://tools.ietf.org/html/rfc7159#section-2), and modify it to suit.

**Comment by laktak** [comment]
A rfc draft and [SABNF](https://github.com/ldthomas/apg-js2/blob/master/SABNF.md) grammar is now up [here](https://github.com/laktak/hjson/tree/master/rfc).
