### ISSUE TITLE
Consider creating a Chocolatey package for the Windows cli

### ISSUE THREAD

**Issue by nshenoy** [laktak/hjson#40]
The readme states that "Nuget does not install commandline tools". Consider creating a Chocolatey package, which is a Nuget based installer for exactly this purpose. Visit Chocolatey.org for details.

**Comment by laktak** [comment]
https://chocolatey.org/packages/hjson/1.14.3

Pending review. Let me know if it works.

**Comment by laktak** [comment]
Live & approved.
