### ISSUE TITLE
Is it possible to minify HJSON?

### ISSUE THREAD

**Issue by gregorypratt** [laktak/hjson#42]
How can we minify our HJSON config files?

This might be a niche use-case but if we want to read our HJSON files client side we'll want to minify them, send them over the wire and parse them without reversing the minification.

Is this possible?

**Comment by laktak** [comment]
Hjson is for humans. So don't minify.

If you use it for something like resources you would write it in Hjson and then convert and minify it to JSON (e.g. with gulp-hjson) for distribution.

**Comment by gregorypratt** [comment]
Got it!
