### ISSUE TITLE
Round-trip fails for keys starting with "#" (and probably other comment characters)

### ISSUE THREAD

**Issue by paulcsyapse** [laktak/hjson#44]
To reproduce in Python 2.7.10 with hjson-1.5.4

```
import hjson
s = '{"#" : 123}'

print hjson.loads(s)
print hjson.dumps(hjson.loads(s))
print hjson.loads(hjson.dumps(hjson.loads(s)))
print hjson.dumps(hjson.loads(hjson.dumps(hjson.loads(s))))
```
outputs
```
OrderedDict([(u'#', 123)])
{
  #: 123
}
OrderedDict()
{}
```

Note that the unquoted # turns the line into a comment, causing it to be lost in the round trip.

**Comment by laktak** [comment]
Thanks for the bug report!

**Comment by jeremycarroll** [comment]
More generally this seems to be a problem with hjson.dumps and keys that must be quoted. We also have an issue with keys including :

**Comment by laktak** [comment]
Should be fixed for python + js. Others will follow.

**Comment by laktak** [comment]
Fixed in java & c# as well.
