### ISSUE TITLE
Quoteless string containing hash # fails to compile

### ISSUE THREAD

**Issue by rezoner** [laktak/hjson#45]
I guess it has something to do with # comments - so maybe the fix would be to check if # is the first char in a row.

```javascript
{
  button: {
    background: #ff0000
  }
}
```

**Comment by laktak** [comment]
Sorry but since # is a comment you need quotes for this: `background: "#ff0000"`

**Comment by rezoner** [comment]
I don't mean to be invasive but `#` comments in the middle of a line work only in that single case when it's exactly after `:` and what would be use of that?

For example # in a text converts to a string anyway. So I am calling you to reconsider making # convert to a comment  only if it's a first char in a row.

```
{
  text: this # will not be a comment anyway - it translates to String
  text: # this throws error - but why would I ever want such construct?
}
```

**Comment by laktak** [comment]
> I don't mean to be invasive but # comments in the middle of a line work only in that single case when it's exactly after : and what would be use of that?

That's not true. Although it is recommended to put comments on their own line, the following is still valid:

```
num: 5 # comment
bool: true # comment
str: "string" # comment
```
