### ISSUE TITLE
How do you think about supporting C++14 style numeric format?

### ISSUE THREAD

**Issue by SangGuKim** [laktak/hjson#46]
The HJson is the exact solution for me to make config files, but I still need some additional features.

The recent C++14 added new integer literals and I think it is really cool stuff. I hope the HJson support it as well.
http://en.cppreference.com/w/cpp/language/integer_literal

digit seperator:    10'000'000
binary:    0b1010'1111

How do you think of it?

**Comment by laktak** [comment]
One of the main goals of Hjson is to keep it simple. While this looks interesting I think it is more important to keep the grammar small.
