### ISSUE TITLE
When a line contains braces and string value, hjson report error. Is this a bug or design? 

### ISSUE THREAD

**Issue by yanghuabei** [laktak/hjson#49]
<img width="1280" alt="2016-06-03 18 22 05" src="https://cloud.githubusercontent.com/assets/6822885/15776081/27da38ce-29b8-11e6-91e9-f9109cb08ccb.png">

I tried boolean and number value, it's ok. So I think it might be a bug.

**Comment by laktak** [comment]
You need to use quotes `"` for string values. A `'` is interpreted to be part of an unquoted string, so you get `'aaa'}` (because it ends at LF).
