### ISSUE TITLE
Fails to parse if ending "}" is in the same line

### ISSUE THREAD

**Issue by tobeorla** [laktak/hjson#51]
This json will throw:
```js
{
"title": { 
	english: 'Romero' }
}
```

> Error: End of input while parsing an object (did you forget a closing '}'?) at line 4,2 >>>} ...

If i add a newline, it works:
```js
{
"title": { 
	english: 'Romero'
}
}
```

:S

**Comment by laktak** [comment]
You are using single quotes so Hjson thinks it's a unquoted string.

Use double quotes: `{ title: { english: "Romero" } }`
